defaults: &steps
  steps:
      - checkout
      - run:
          name: Install dev version of devtools
          command: |
            R \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_github("r-lib/devtools")'
      - run:
          name: Install package dependencies
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - run:
          name: Check and test
          command: |
            R -e 'results <- devtools::check(); stopifnot(length(results$errors) == 0)'

version: 2
jobs:

  "r-3.4.2":
     docker:
       - image: rocker/geospatial:3.4.2
     <<: *steps

  "r-3.4.3":
     docker:
       - image: rocker/geospatial:3.4.3
     <<: *steps

  "r-release":
     docker:
       - image: rocker/geospatial:latest
     <<: *steps

  "r-devel":
     docker:
       - image: rocker/geospatial:devel
     <<: *steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - "r-3.4.2"
      - "r-3.4.3"
      - "r-release"
      - "r-devel"

