defaults: &steps
  steps:
    - checkout

    ## install dev devtools -------------------------------

    - run:
        name: Install dev version of devtools
        command: |
          Rscript \
          -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
          -e 'devtools::install_github("r-lib/devtools")'

    ## setup -------------------------------

    - run:
        name: Set environmental variables
        command: |
          Rscript --vanilla \
            -e 'dsc <- read.dcf("DESCRIPTION")' \
            -e 'cat(sprintf("export PKG_TARBALL=%s_%s.tar.gz\n", dsc[,"Package"], dsc[,"Version"]))' \
            -e 'cat(sprintf("export RCHECK_DIR=%s.Rcheck\n", dsc[,"Package"]))' \
            >> ${BASH_ENV}

    ## install dependencies ------------------

    - run:
        name: Install devtools and dependencies
        command: |
          Rscript \
            -e 'devtools::install_deps(dependencies = TRUE)'

    ## check and test with devtools -----------------

    - run:
        name: Check package
        command: Rscript -e 'devtools::check()'

version: 2
jobs:
  "r-release":
     docker:
       - image: rocker/tidyverse:latest
     <<: *steps

  "r-devel":
     docker:
       - image: rocker/tidyverse:devel
     <<: *steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - "r-release"
      - "r-devel"

