version: 2
jobs:
  linux:
    docker:
      - image: bocinsky/bocin_base:latest
    steps:
      - checkout
      - run:
          name: Install remotes
          command: |
              R \
                -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
                -e 'devtools::install_cran("remotes")'
      - run:
          name: Install
          command: |
              R -e 'devtools::install(".", dependencies = TRUE, upgrade_dependencies = FALSE)'
      - run:
          name: Install remote dependencies
          command: |
              R -e 'remotes::install_local(".")'
      - run:
          name: Check and test
          command: |
              R -e 'results <- devtools::check(vignettes = FALSE, args = "--no-vignettes"); stopifnot(length(results$errors) == 0)'
  mac:
    macos:
      xcode: "9.0"
    steps:
      - checkout
      - run:
          name: Update homebrew
          command: brew update
          no_output_timeout: 1h
      - run:
          name: Upgrade homebrew
          command: brew upgrade
          no_output_timeout: 1h
      - run:
          name: Install r
          command: brew cask install r-app
          no_output_timeout: 1h
      - run:
          name: Install gdal
          command: brew install gdal --with-complete --with-unsupported
          no_output_timeout: 1h
      - run:
          name: Install ffmpeg
          command: brew install ffmpeg
          no_output_timeout: 1h
      - run:
          name: Install ghostscript
          command: brew install ghostscript
          no_output_timeout: 1h
      - run:
          name: Install protobuf
          command: brew install protobuf
          no_output_timeout: 1h
      - run:
          name: Install v8@3.15
          command: brew install v8@3.15
          no_output_timeout: 1h
      - run:
          name: Install pandoc
          command: brew install pandoc
          no_output_timeout: 1h
      - run:
          name: Install pandoc-citeproc
          command: brew install pandoc-citeproc
          no_output_timeout: 1h
      - run:
          name: Install remotes
          command: |
            R \
              -e 'options(repos = "https://cloud.r-project.org/")' \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_cran("remotes")' \
              -e 'devtools::install_cran("rmarkdown")' \
              -e 'devtools::install_cran("roxygen2")'
      - run:
          name: Install
          command: |
            R -e 'devtools::install(".", dependencies = TRUE, upgrade_dependencies = FALSE)'
      - run:
          name: Install remote dependencies
          command: |
            R -e 'remotes::install_local(".")'
      - run:
          name: Check and test
          command: |
            R -e 'results <- devtools::check(vignettes = FALSE, args = "--no-vignettes"); stopifnot(length(results$errors) == 0)'
workflows:
  version: 2
  build_and_test:
    jobs:
      - linux
      - mac
