version: 2
jobs:
  build:
    docker:
      - image: bocinsky/asian_niche:latest
    steps:
      - checkout
      - run: 
          name: build
          command: docker build -t bocinsky/asian_niche .
      - run:
          name: test
          command: docker run --name asian_niche -d -p 8787:8787 bocinsky/asian_niche


