defaults: &steps
  steps:
      - checkout
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
            - deps1-{{ .Branch }}
            - deps1-
      - run:
          name: Install dev version of devtools
          command: |
            Rscript \
              -e 'if (!requireNamespace("devtools", quietly = TRUE)) install.packages("devtools")' \
              -e 'devtools::install_github("r-lib/devtools")'
      - run:
          name: Install package dependencies
          command: |
            R -e 'devtools::install_deps(dependencies = TRUE)'
      - save_cache:
          name: Save cache
          key: deps1-{{ .Branch }}-{{ checksum "DESCRIPTION" }}
          paths:
            - "/usr/local/lib/R/site-library"
      - run:
          name: Check and test
          command: |
            R -e 'results <- devtools::check(); stopifnot(length(results$errors) == 0)'
      - store_artifacts:
          path: man/
          destination: man

version: 2
jobs:
  "r-release":
     docker:
       - image: rocker/tidyverse:latest
     <<: *steps

  "r-devel":
     docker:
       - image: rocker/tidyverse:devel
     <<: *steps

workflows:
  version: 2
  build_and_test:
    jobs:
      - "r-release"
      - "r-devel"

